### ISSUE TITLE
BLOC导致代码逻辑像被混淆了一样……

### ISSUE THREAD

**Issue by mjl0602** [Hu-Wentao/race_demo#1]
没有接触过BLOC的模式，但是读下来感觉全部都在往流里扔事件，再自己接收，就像是代码混淆把函数全部包进一个大循环里。看不出彼此先后顺序与逻辑关系了。

**Comment by mjl0602** [comment]
主要是在OAD这一块，不过兄弟你是GitHub上第一个dart写OAD逻辑的人，佩服佩服

**Comment by Hu-Wentao** [comment]
BLoC确实是这样, 不过这个项目已经弃坑很久了, 后来用的是Provider
